name: Release
on: [workflow_dispatch] # Manual trigger

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: eclipse-temurin:17-jdk
      options: --user root
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: 'BookkeepersMC/m2'
          path: m2
          ref: master
          token: ${{ secrets.GIT_PAT }}
      - uses: gradle/actions/wrapper-validation@v3
      - run: ./gradlew build publish --stacktrace

      - uses: EndBug/add-and-commit@v9.1.4
        with:
          add: './com/'
          default_author: github_actions
          cwd: "./m2/"
          message: "Publish loom native"